### ISSUE TITLE
Referencing Components

### ISSUE THREAD

**Issue by vritant24** [vritant24/cleave-html#2]
Would we want to create sort of import statements on top of html files so we know which component they're referencing? If not, creating a whole 'sample space' of all possible components, and then checking whether a referenced component exits would be more inefficient than DFSing through files and finding referenced components. 

The imports could be done within comments, for eg.

**Comment by claytn** [comment]
I think imports of some sort would better. And since we aren't directly using the html they provide I think it would be fine if we just allowed for es6 import statements or something similar. Any syntax outside of html just wouldn't be used within the final output file.

**Comment by vritant24** [comment]
Yeah that makes sense. So what kind of files would they be? Normal text editors would freak out with both HTML and JS syntax in the same file. 
Putting import statements in comments could be a way around that

**Comment by claytn** [comment]
Yeah that would work. Since we are already going to have to parse the entire file anyway, what if we only imported things as they appear. For example, if inside a <div> there is a <Description> module used. We can just import the Description modules from a separate file when we see that Description is not an html element. Then we recursively parse the Description component. Recursing through multiple modules might get a bit tricky, but we will deal with that when the time comes. What do you think about this style of implicit imports?

**Comment by vritant24** [comment]
By implicit imports do you mean 'see a tag, if it's not inbuilt, find the file and parse and inline'?
